job_salary:
  target: dev
  outputs:
    dev:
      type: trino
      method: none
      http_scheme: http
      host: trino            
      port: 8080
      catalog: iceberg
      schema: gold                 
      user: admin
      threads: 4