connector.name=clickhouse

connection-url=jdbc:clickhouse://clickhouse:8123/?socket_timeout=300000&http_connection_provider=HTTP_CLIENT

connection-user=user
connection-password=user

insert.non-transactional-insert.enabled=true
