connector.name=delta_lake
delta.minio.endpoint=http://minio:9000
delta.minio.access-key=minio
delta.minio.secret-key=minio123
delta.minio.path-style-access=true
delta.native-s3.enabled=true
s3.region=us-east-1